THMtest/THMtest/urls.py
from django.contrib import admin
from django.urls import path
from alagator.views import create_view,Home

urlpatterns = [
    path('admin/', admin.site.urls),
    path('/registrar', create_view.as_view(),name='registrar'),
    path('/', Home.as_view,name='home'),
    
]

THMtest/alagator/models.py
from django.db import models
from datetime import datetime
# Create your models here.

class Usuario(models.Model):
	username= models.CharField(
		max_length=50,
		blank=False,
		null=False,
		unique=True
	)
	nome = models.CharField(
		max_length = 50,
		blank = False,
		null = False
	)

	sobrenome = models.CharField(
		max_length = 50,
		blank = False,
		null = False
	)
	email = models.EmailField(
		max_length = 70,
		blank = False,
		unique = True
	)

	def __str__(self):
		return "%s %s" % (self.nome, self.sobrenome)


class Local(models.Model):
	cep = models.CharField(
		max_length = 9,
		blank = True,
		null = True
	)
	cidade = models.CharField(
		max_length = 50,
		blank = False,
		null = False
	)
	bairro = models.CharField(
		max_length = 50,
		blank = False,
		null = False
	)
	logradouro = models.CharField(
		max_length = 50,
		blank = False,
		null = False
	)
	uf = models.CharField(
		max_length = 2,
		blank = False,
		null = False
	)

	def __str__(self):
		return "%s, %s, %s, %s, %s" % (
			self.logradouro,
			self.bairro,
			self.cidade,
			self.uf,
			self.cep
		)

class Alagamento(models.Model):
	LEVE = 'LEVE'
	MODERADO = 'MODERADO'
	GRAVE = 'GRAVE'
	INTENSIDADE = (
		(LEVE,LEVE),
		(MODERADO,MODERADO),
		(GRAVE,GRAVE)
	)
	LOCALIZADO = 'LOCALIZADO'
	INTRANSITAVEL = 'INTRANSITAVEL'
	CLASSIFICACAO = (
		(LOCALIZADO,LOCALIZADO),
		(INTRANSITAVEL,INTRANSITAVEL)
	)

	reg_date = models.DateTimeField( 
		auto_now_add=True,

	)

	intensidade = models.CharField(
		max_length=20, 
		choices = INTENSIDADE, 
		default=LEVE
	)

	classificacao = models.CharField(
		max_length=20,
		choices = CLASSIFICACAO,
		default = LOCALIZADO
	)

	img1 = models.ImageField(null=True,blank=True)

	img2 = models.ImageField(null=True,blank=True)

	local = models.ForeignKey(Local, on_delete=models.CASCADE)

	usuario = models.ForeignKey(Usuario, on_delete=models.CASCADE)

	def __str__(self):
		return str(self.local) + "(" +self.intensidade + "), " + str(self.reg_date)

THMtest/alagator/forms.py
from django import forms
from .model import Usuario,Local,Alagamento

class LoginUsuario(form.ModelsForm):
	template_name = "index.html"
	class Meta:
		model = Usuario
		fields = ('username','email')

class RegistroUsuario(form.ModelForm):
	class Meta:
		model = Usuario
		fields = ('username', 'nome','sobrenome','email')

THMtest/alagator/views.py
from django.shortcuts import render, redirect
from .form import RegistroUsuario, LoginUsuario
from .model import Usuario, Local, Alagamento
# Create your views here.

class Home(View):
	context = {}

	def get(self,request):
		valido =False
		form = LoginUsuario()
		self.context['valido'] = valido
		self.context['form']= form
		self.context['alagamento'] = Alagamento.objects.all()
		return render(request,'index.html',self.context)

	def post(self,request):
		valido = False

		form = LoginUsuario(request.POST)
		if form.is_valid():
			username = form.cleaned_data.get('username')
			email = form.cleaned_data.get('email')
			for usuario in Usuario.objects.all():
				if(usuario.username == username && usuario.email == email):
					valido = True
					user = usuario
		self.context['form'] = form
		self.context['valido'] = valido
		self.context['alagamento'] = Alagamento.objects.all()
		self.context['user'] = user
		return render(request, 'index.html', self.context)


class Registro(View):
	context={}
	def get(self,request):
		form = RegistroUsuario()
		self.context['form'] = form
		return render(request,'registro.html',self.context)
	def post(self,request):
		form = RegistroUsuario(request.POST)
		if form.is_valid():
			form.save()
			return HttpResponseRedirect(reverse('/'))

		self.context['form'] = form
		return render(request,"registro.html", self.context)

THMtest/alagator/templates/index.html
<!DOCTYPE html>
<html lang = "pt-br">
<head>
	<link rel="stylesheet" href="../static/styles/index.css"
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width,initial-scale=1.0">
	<title>Alagator - Serviço de Registro de Alagamentos</title>
</head>
<body>
	<div class ="upper_body">
		{% if valido %}
		<div class="main_left_user">
			<img class="img_logo_user" src="../static/imgs/logo.png" alt="logo">
		</div>
		<div class="main_right_user">
			<span class="ola_tag">Olá,{{user.username}}!</span>
			<span class="registro_tag">Total de Registros: {{ user.alagamento_set.count }}</span>
			<a class="registro_alagamento" href="registro_alagamento">Registrar de Alagamento</a>
		</div>
		{% else %}
		<div class="main_left">
			<img class="img_logo" src="../static/imgs/logo.png" alt="logo">
		</div>
		<div class="main_right">
			<form class="form_main" method="POST">
				<!--<input class="text_input" type="text" name="username" placeholder="Username">
				<input class="text_input" type="text" name="email" placeholder="Email">-->
				{% csrf_token %}
        		{{ form.username }}
        		{{ form.email }}
				<button class="button_input" type="submit">Login</button>
				<a class="tag_cadastro" href="/registrar">Cadastre-se</a>
			</form>
		</div>
		{% endif %}
	</div>
	<div class="lower_body">
		<ul>
			{% for ocorrencia in alagamento %}
			<li>
				<span class="int_text">{{ocorrencia.intensidade}}/{{ocorrencia.classificacao}}</span>
				<span class="loc_tex">{{str(ocorrencia.local)}}</span>
			</li>
			{% endfor %}
		</ul>
	</div>
</body>
</html>

THMtest/alagator/templates/registro.html
<!DOCTYPE html>
<html lang = "pt-br">
<head>
	<link rel="stylesheet" href="../static/styles/registro.css"
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width,initial-scale=1.0">
	<title>Alagator - Serviço de Registro de Alagamentos</title>
</head>
<body>
	<div class ="body">
		<div class="main_left">
			<h1 class="titulo">Registrar Usuário</h1>
		</div>
		<div class="main_right">
			<form class="form_main" method="POST">
				<input class="text_input" type="text" name="username" placeholder="Username">
				<input class="text_input" type="text" name="nome" placeholder="Nome">
				<input class="text_input" type="text" name="sobrenome" placeholder="Sobrenome">
				<input class="text_input" type="text" name="email" placeholder="Email">

				<button class="button_input" type="submit">Cadastre-se</button>
				<a class="tag_cadastro" href="/registrar">Login</a>
			</form>
		</div>
		
	</div>
</body>
</html>

THMtest/alagator/templates/registroAlagamento.html
<!DOCTYPE html>
<html lang = "pt-br">
<head>
	<link rel="stylesheet" href="../static/styles/registroAlagamento.css"
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width,initial-scale=1.0">
	<title>Alagator - Serviço de Registro de Alagamentos</title>
</head>
<body>
	<div class ="body">
		<div class="main_left">
			<h1 class="titulo">Registrar Alagamento</h1>
		</div>
		<div class="main_right">
			<form class="form_main" method="POST">
				<input class="text_input" id="cep" type="text" name="cep" placeholder="CEP">
				<input class="text_input" id="logradouro"type="text" name="logradouro" placeholder="Logradouro">
				<input class="text_input" id="bairro" type="text" name="bairro" placeholder="Bairro">
				<input class="text_input" id="cidade" type="text" name="cidade" placeholder="Cidade">
				<input class="text_input" id="uf" type="text" name="uf" placeholder="UF">
				<select>
					<option selected="selected">Selecionar Intensidade:</option>
    				<option value="1">Leve</option>
   					<option value="2">Moderado</option>
   					<option value="3">Grave</option>
				</select>
				<select>
					<option selected="selected">Selecionar Classificação:</option>
    				<option value="1">Localizado</option>
   					<option value="2">Intrasitável</option>
				</select>
				<input type="file" accept="image/*,.pdf" name="imagem1"/>
				<input type="file" accept="image/*,.pdf" name="imagem2"/>
				<button class="button_input" type="submit">Registrar</button>
			</form>
		</div>
		
	</div>

	<script src="https://code.jquery.com/jquery-3.0.0.min.js"></script>
	<script>
			$("#cep").blur(function(){
				var cep = this.value.replace(/[^0-9]/, "");
				if(cep.length != 8){
					return false;
				}
				var url = "https://viacep.com.br/ws/"+cep+"/json/";
				
				$.getJSON(url, function(dadosRetorno){
					try{
						$("#logradouro").val(dadosRetorno.logradouro);
						$("#bairro").val(dadosRetorno.bairro);
						$("#cidade").val(dadosRetorno.localidade);
						$("#uf").val(dadosRetorno.uf);
					}catch(ex){}
				});
			});
		</script>
</body>
</html>

THMtest/alagator/templates/registroEndereco.html
<!DOCTYPE html>
<html lang = "pt-br">
<head>
	<link rel="stylesheet" href="../static/styles/registroEndereco.css"
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width,initial-scale=1.0">
	<title>Alagator - Serviço de Registro de Alagamentos</title>
</head>
<body>
	<div class ="body">
		<div class="main_left">
			<h1 class="titulo">Registrar Endereço</h1>
		</div>
		<div class="main_right">
			<form class="form_main" method="POST">
				<input class="text_input" type="text" name="cep" placeholder="CEP">
				<input class="text_input" type="text" name="logradouro" placeholder="Logradouro">
				<input class="text_input" type="text" name="bairro" placeholder="Bairro">
				<input class="text_input" type="text" name="cidade" placeholder="Cidade">
				<input class="text_input" type="text" name="uf" placeholder="UF">

				<button class="button_input" type="submit">Registrar</button>
			</form>
		</div>
		
	</div>
</body>
</html>

THMtest/alagator/templates/user.html
<!DOCTYPE html>
<html lang = "pt-br">
<head>
	<link rel="stylesheet" href="../static/styles/user.css"
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width,initial-scale=1.0">
	<title>Alagator - Serviço de Registro de Alagamentos</title>
</head>
<body>
	<div class ="upper_body">
		<div class="main_left_user">
			<img class="img_logo" src="../static/imgs/logo.png" alt="logo">
		</div>
		<div class="main_right_user">
			<span class="ola_tag">Olá,UsuárioTeste!</span>
			<span class="registro_tag">Total de Registros: 30000</span>
			<a class="registro_alagamento" href="registro_alagamento">Registrar de Alagamento</a>
		</div>
		
	</div>
	<div class="lower_body">
		<ul>
			<li>
				<span class="int_text">Intesidade1/Categoria</span>
				<span class="loc_tex">Localização</span>
			</li>
			<li>
				<span class="int_text">Intesidade2/Categoria</span>
				<span class="loc_tex">Localização</span>
			</li>
			<li>
				<span class="int_text">Intesidade3/Categoria</span>
				<span class="loc_tex">Localização</span>
			</li>
			<li>
				<span class="int_text">Intesidade1/Categoria</span>
				<span class="loc_tex">Localização</span>
			</li>
			<li>
				<span class="int_text">Intesidade2/Categoria</span>
				<span class="loc_tex">Localização</span>
			</li>
			<li>
				<span class="int_text">Intesidade3/Categoria</span>
				<span class="loc_tex">Localização</span>
			</li>
			<li>
				<span class="int_text">Intesidade1/Categoria</span>
				<span class="loc_tex">Localização</span>
			</li>
			<li>
				<span class="int_text">Intesidade2/Categoria</span>
				<span class="loc_tex">Localização</span>
			</li>
			<li>
				<span class="int_text">Intesidade3/Categoria</span>
				<span class="loc_tex">Localização</span>
			</li>
			<li>
				<span class="int_text">Intesidade1/Categoria</span>
				<span class="loc_tex">Localização</span>
			</li>
			<li>
				<span class="int_text">Intesidade2/Categoria</span>
				<span class="loc_tex">Localização</span>
			</li>
			<li>
				<span class="int_text">Intesidade3/Categoria</span>
				<span class="loc_tex">Localização</span>
			</li>
			<li>
				<span class="int_text">Intesidade1/Categoria</span>
				<span class="loc_tex">Localização</span>
			</li>
			<li>
				<span class="int_text">Intesidade2/Categoria</span>
				<span class="loc_tex">Localização</span>
			</li>
			<li>
				<span class="int_text">Intesidade3/Categoria</span>
				<span class="loc_tex">Localização</span>
			</li>
		</ul>
	</div>
</body>
</html>